# Color Palette: Pink (#ff007f), Blue (#33ccff), Green (#00ff99), Yellow (#ffee00), Purple (#9d00ff)
# Background: Deep Obsidian (#0d0d17)

# Basic Colors
foreground            #c0caf5
background            #0d0d17
selection_foreground  #0d0d17
selection_background  #33ccff

# Cursor colors
cursor                #ff007f
cursor_text_color     #0d0d17

# URL underline color
url_color             #00ff99

# Kitty window border colors
active_border_color     #ff007f
inactive_border_color   #1b1b2b
bell_border_color       #33ccff

# Tab bar colors
active_tab_foreground   #0d0d17
active_tab_background   #ff007f
inactive_tab_foreground #787c99
inactive_tab_background #161626
tab_bar_background      #0d0d17

# The 16 terminal colors

# black
color0 #0d0d17
color8 #414868

# red (Cyberpunk Pink)
color1 #ff007f
color9 #ff33a1

# green (Neon Green)
color2  #00ff99
color10 #26ffaa

# yellow (Hazard Yellow)
color3  #ffee00
color11 #fff700

# blue (Neon Blue)
color4  #33ccff
color12 #52d5ff

# magenta (NOW ff6600Electric Violet)
color5  #9d00ff
color13 #b042ff

# cyan (actually orange)
color6  #ff6600
color14 #ff8533

# white
color7  #a9b1d6
color15 #c0caf5
