bind-key -n C-W if-shell -F '#{?#{==:#{pane_current_command},bash},0,#{?#{==:#{pane_current_command},zsh},0,#{?#{==:#{pane_current_command},fish},0,#{?#{==:#{pane_current_command},sh},0,1}}}}' \
    "confirm-before -p 'Process #{pane_current_command} is running. Kill pane? (y/n)' 'kill-pane ; select-layout -E ; refresh-client'" \
    "kill-pane ; select-layout -E ; refresh-client"
