#!/usr/bin/env python3
"""Render the two states of the waybar custom/jellyfin glyph.

Same visual language as the other bar icons: white on transparent, with
the same translucent-white "dimmed" convention generate_bluetooth_icons.py
uses for its unlit state, rather than a separate grey.

The glyph is the Jellyfin project's icon mark -- two overlapping droplet
shapes, path data lifted from jellyfin-ux's icon-transparent.svg
(https://github.com/jellyfin/jellyfin-ux, CC-BY-SA 4.0) -- recolored flat
white instead of the official purple/blue gradient to match the rest of
the bar:
  on.svg:  both shapes solid white (server running)
  off.svg: both shapes dimmed (translucent white) (server stopped)

Output: waybar/icons/jellyfin/{on,off}.svg, plus
waybar/jellyfin-icons-generated.css, which style.css @imports, mapping
"on"/"off" classes (set by hypr/jellyfin_status.sh) to the matching
background-image.

Run manually to regenerate: ./generate_jellyfin_icons.py
"""
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ICONS_DIR = ROOT / "icons" / "jellyfin"
CSS_OUT = ROOT / "jellyfin-icons-generated.css"

WHITE = "#ffffff"
DIM_OPACITY = "0.3"

# Outer ring (a single path whose two subpaths wind in opposite directions,
# punching the hole) and inner droplet, verbatim from the official mark.
OUTER = (
    "M256,23.3c-61.6,0-259.8,359.4-229.6,420.1s429.3,60,459.2,0S317.6,23.3,256,23.3z"
    "M406.5,390.8c-19.6,39.3-281.1,39.8-300.9,0s110.1-275.3,150.4-275.3S426.1,351.4,406.5,390.8z"
)
INNER = "M256,201.6c-20.4,0-86.2,119.3-76.2,139.4s142.5,19.9,152.4,0S276.5,201.6,256,201.6z"


def glyph(opacity):
    return (
        f'<path d="{OUTER}" fill="{WHITE}" fill-opacity="{opacity}"/>'
        f'<path d="{INNER}" fill="{WHITE}" fill-opacity="{opacity}"/>'
    )


def svg(shapes):
    # 512x512 viewBox is already plenty of intrinsic resolution (bigger
    # than the up-scaled sizes the other generators target), so unlike
    # generate_battery_icons.py etc. there's no need to inflate width/height
    # past the viewBox.
    return f'<svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">{shapes}</svg>'


def main():
    if ICONS_DIR.exists():
        shutil.rmtree(ICONS_DIR)
    ICONS_DIR.mkdir(parents=True)

    on_path = ICONS_DIR / "on.svg"
    off_path = ICONS_DIR / "off.svg"
    on_path.write_text(svg(glyph("1")))
    off_path.write_text(svg(glyph(DIM_OPACITY)))

    css = (
        "/* GENERATED by generate_jellyfin_icons.py -- do not edit by hand */\n"
        f'#custom-jellyfin.on {{ background-image: url("file://{on_path}"); }}\n'
        f'#custom-jellyfin.off {{ background-image: url("file://{off_path}"); }}\n'
    )
    CSS_OUT.write_text(css)
    print(f"Wrote {on_path} and {off_path}")
    print(f"Wrote {CSS_OUT}")


if __name__ == "__main__":
    main()
