#!/usr/bin/env python3
"""Render the waybar custom/language glyph: a white rounded square with the
language's first letter knocked out as a transparent cutout (same mask
technique as the very first battery gauge design) -- white square, see-
through letter, nothing else.

hypr/keyboard_layout.py (the runtime poller) derives its class name
automatically from whatever Hyprland reports as the active keymap: it
lowercases the keymap's first word (e.g. "English (US)" -> "english",
"Georgian" -> "georgian") and uses that directly as the CSS class, with no
lookup table of its own. So at runtime, adding a language needs nothing
changed in that script -- but this generator's LANGUAGES dict is the one
place that turns a code into an actual icon, and it can't be filled in
automatically: enumerating every layout's display name would mean actually
switching the keyboard into each one and reading back hyprctl's report, so
the two currently configured layouts (kb_layout = us,ge in hyprland.conf)
are just listed here directly, keyed by that same derived code.

To add a language once you've added its layout to kb_layout in
hyprland.conf:
  1. Switch to the new layout (hyprctl switchxkblayout all next, or however
     many times it takes), then run:
       hyprctl devices -j | jq -r '.keyboards[] | select(.name=="at-translated-set-2-keyboard") | .active_keymap'
     to see the exact display name Hyprland reports for it.
  2. Add a "code": (display_name, letter) entry to LANGUAGES below -- code
     must be display_name's first word, lowercased, to match what
     hypr/keyboard_layout.py derives at runtime. letter should be that
     language's own first letter *in its own script* -- e.g. Georgian
     shows "ქ" (Georgian qari), not "G" -- since hyprctl's
     active_keymap is always the English name of the layout regardless of
     what script the language itself uses, that letter can't be derived
     automatically the way the code/class can; look up the language's
     native name and take its first letter by hand. If it's just a Latin-
     script language, pass None and it defaults to display_name[0].upper().
  3. Run ./generate_language_icons.py again and restart waybar.

Non-Latin letters need a font that actually has that script -- DejaVu Sans
covers Latin/Cyrillic/Greek reasonably but not much beyond that, so the
font-family list below adds Noto Sans <script> fallbacks as they come up
(only Georgian so far). If a new language's letter renders as a blank box
("tofu"), that's a missing font-family fallback, not a bug in the mask
technique -- check `fc-list :lang=<iso-code>` for what's installed and add
its Noto family to FONT_FAMILY.

Output: waybar/icons/language/{code}.svg, plus
waybar/language-icons-generated.css, which style.css @imports, mapping
each "<code>" class (set by hypr/keyboard_layout.py) to its background-image.

Run manually to regenerate: ./generate_language_icons.py
"""
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ICONS_DIR = ROOT / "icons" / "language"
CSS_OUT = ROOT / "language-icons-generated.css"

WHITE = "#ffffff"
FONT_FAMILY = "SF Pro, DejaVu Sans, Noto Sans Georgian, sans-serif"

# code (= display name's first word, lowercased) -> (display name as
# reported by `hyprctl devices -j`'s active_keymap, letter to show). letter
# is the language's own first letter in its own script where that differs
# from the English display name -- None defaults to display_name[0].upper().
LANGUAGES = {
    "english": ("English (US)", None),
    "georgian": ("Georgian", "ქ"),  # ქ, from ქართული (Kartuli) -- Georgian's own name for itself
}


def language_svg(letter):
    return f'''<svg width="320" height="320" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
  <mask id="m">
    <rect x="1" y="1" width="18" height="18" rx="4" fill="white"/>
    <text x="10" y="14.5" text-anchor="middle" font-size="13" font-weight="800"
          font-family="{FONT_FAMILY}" fill="black">{letter}</text>
  </mask>
  <rect x="1" y="1" width="18" height="18" rx="4" fill="{WHITE}" mask="url(#m)"/>
</svg>'''


def main():
    if ICONS_DIR.exists():
        shutil.rmtree(ICONS_DIR)
    ICONS_DIR.mkdir(parents=True)

    css_rules = ["/* GENERATED by generate_language_icons.py -- do not edit by hand */"]
    for code, (display_name, letter) in LANGUAGES.items():
        letter = letter or display_name[0].upper()
        out_path = ICONS_DIR / f"{code}.svg"
        out_path.write_text(language_svg(letter))
        css_rules.append(f'#custom-language.{code} {{ background-image: url("file://{out_path}"); }}')

    CSS_OUT.write_text("\n".join(css_rules) + "\n")
    print(f"Wrote {len(list(ICONS_DIR.glob('*.svg')))} icons to {ICONS_DIR}")
    print(f"Wrote {CSS_OUT}")


if __name__ == "__main__":
    main()
