#!/usr/bin/env python3
"""Render the two states of the waybar custom/bluetooth glyph.

Same visual language as the battery/wifi gauges: white on transparent, with
the same translucent-white "dimmed" convention generate_wifi_icons.py uses
for its unlit bars, rather than a separate grey.

The glyph itself is the standard bluetooth rune (a single open zig-zag
stroke) -- path lifted from Lucide's bluetooth icon (MIT licensed), just
drawn bolder to match the other bar icons' weight:
  on.svg:  full glyph, solid white
  off.svg: full glyph dimmed (translucent white) plus a solid diagonal
           strike-through, same idea as a muted-mic icon

Output: waybar/icons/bluetooth/{on,off}.svg, plus
waybar/bluetooth-icons-generated.css, which style.css @imports, mapping
"on"/"connected"/"off" classes (set by bluetooth_status.sh) to the matching
background-image.

Run manually to regenerate: ./generate_bluetooth_icons.py
"""
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ICONS_DIR = ROOT / "icons" / "bluetooth"
CSS_OUT = ROOT / "bluetooth-icons-generated.css"

WHITE = "#ffffff"
DIM_OPACITY = "0.3"
STROKE_WIDTH = 1.8

# The bluetooth rune, as a single open polyline: top -> lower-right corner ->
# bottom-center -> top-center -> upper-right corner -> bottom-left corner.
GLYPH_POINTS = "7,7 17,17 12,22 12,2 17,7 7,17"


def glyph(opacity):
    return (
        f'<polyline points="{GLYPH_POINTS}" fill="none" stroke="{WHITE}" '
        f'stroke-opacity="{opacity}" stroke-width="{STROKE_WIDTH}" '
        f'stroke-linecap="round" stroke-linejoin="round"/>'
    )


SLASH = (
    f'<line x1="6" y1="6" x2="18" y2="18" stroke="{WHITE}" stroke-opacity="{DIM_OPACITY}" '
    f'stroke-width="{STROKE_WIDTH}" stroke-linecap="round"/>'
)


def svg(shapes):
    # Large intrinsic width/height (vs. the 24x24 viewBox) for the same
    # reason as generate_battery_icons.py: GTK's background-image loader
    # rasterizes once at the declared intrinsic size, then stretches that
    # bitmap to the CSS box, so a small intrinsic size makes for a blurry
    # upscale regardless of the eventual display size.
    return f'<svg width="240" height="240" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">{shapes}</svg>'


def main():
    if ICONS_DIR.exists():
        shutil.rmtree(ICONS_DIR)
    ICONS_DIR.mkdir(parents=True)

    on_path = ICONS_DIR / "on.svg"
    off_path = ICONS_DIR / "off.svg"
    on_path.write_text(svg(glyph("1")))
    off_path.write_text(svg(glyph(DIM_OPACITY) + SLASH))

    css = (
        "/* GENERATED by generate_bluetooth_icons.py -- do not edit by hand */\n"
        f'#custom-bluetooth.on, #custom-bluetooth.connected {{ background-image: url("file://{on_path}"); }}\n'
        f'#custom-bluetooth.off {{ background-image: url("file://{off_path}"); }}\n'
    )
    CSS_OUT.write_text(css)
    print(f"Wrote {on_path} and {off_path}")
    print(f"Wrote {CSS_OUT}")


if __name__ == "__main__":
    main()
