#!/usr/bin/env python3
"""Render the ten states of the waybar custom/backlight glyph: a sun whose
rays get longer as brightness increases. White on transparent, same
language as the other bar icons.

Each tier is its own distinct design rather than a superset of the last --
a real sun icon's rays lengthen as it brightens:
  tier1:      0-10%  -> just the disc, no rays
  tier2..10:  10-100%, one 10%-wide band each -> disc + 8 rays, getting
              longer tier over tier (tier10's rays are the longest)

Output: waybar/icons/backlight/tier{1..10}.svg, plus
waybar/backlight-icons-generated.css, which style.css @imports, mapping
"tier1".."tier10" classes (set by backlight_level.py) to the matching
background-image.

Run manually to regenerate: ./generate_backlight_icons.py
"""
import math
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ICONS_DIR = ROOT / "icons" / "backlight"
CSS_OUT = ROOT / "backlight-icons-generated.css"

WHITE = "#ffffff"
VIEW_SIZE = 24.0
CX, CY = VIEW_SIZE / 2, VIEW_SIZE / 2
CORE_R = 4.6  # grown twice now from the original 3.2
# A round linecap extends a ray back by half its stroke-width beyond its
# nominal start point, so GAP needs real clearance past CORE_R for a visible
# gap to survive that -- not just a hair past the disc's edge.
GAP = 2.3
RAY_INNER = CORE_R + GAP
RAY_OUTER_MAX = 10.5
N_TIERS = 10
RAY_OUTER_BY_TIER = {
    tier: RAY_INNER + (tier - 1) * (RAY_OUTER_MAX - RAY_INNER) / (N_TIERS - 1)
    for tier in range(2, N_TIERS + 1)
}
ANGLES = [i * 45 for i in range(8)]


def _point(radius, deg):
    rad = math.radians(deg)
    return CX + radius * math.cos(rad), CY + radius * math.sin(rad)


CORE = f'<circle cx="{CX}" cy="{CY}" r="{CORE_R}" fill="{WHITE}"/>'


def rays(outer_r):
    return "".join(
        f'<line x1="{x0:.3f}" y1="{y0:.3f}" x2="{x1:.3f}" y2="{y1:.3f}" '
        f'stroke="{WHITE}" stroke-width="1.4" stroke-linecap="round"/>'
        for deg in ANGLES
        for x0, y0 in [_point(RAY_INNER, deg)]
        for x1, y1 in [_point(outer_r, deg)]
    )


TIERS = {1: CORE}
TIERS.update({tier: CORE + rays(outer_r) for tier, outer_r in RAY_OUTER_BY_TIER.items()})


def backlight_svg(tier):
    # Large intrinsic width/height (vs. the VIEW_SIZE viewBox) for the same
    # reason as generate_battery_icons.py: GTK's background-image loader
    # rasterizes once at the declared intrinsic size, then stretches that
    # bitmap to the CSS box, so a small intrinsic size makes for a blurry
    # upscale regardless of the eventual display size.
    side = round(VIEW_SIZE * 16)
    return (
        f'<svg width="{side}" height="{side}" viewBox="0 0 {VIEW_SIZE:g} {VIEW_SIZE:g}" '
        f'xmlns="http://www.w3.org/2000/svg">{TIERS[tier]}</svg>'
    )


def main():
    if ICONS_DIR.exists():
        shutil.rmtree(ICONS_DIR)
    ICONS_DIR.mkdir(parents=True)

    css_rules = ["/* GENERATED by generate_backlight_icons.py -- do not edit by hand */"]
    for tier in range(1, N_TIERS + 1):
        out_path = ICONS_DIR / f"tier{tier}.svg"
        out_path.write_text(backlight_svg(tier))
        css_rules.append(f'#custom-backlight.tier{tier} {{ background-image: url("file://{out_path}"); }}')

    CSS_OUT.write_text("\n".join(css_rules) + "\n")
    print(f"Wrote {len(list(ICONS_DIR.glob('*.svg')))} icons to {ICONS_DIR}")
    print(f"Wrote {CSS_OUT}")


if __name__ == "__main__":
    main()
