#!/usr/bin/env python3
"""Render a 10-tier wifi signal gauge for the waybar custom/wifi module.

Same visual language as the volume gauge (generate_volume_icons.py): a
solid "dot" (always fully lit, like the volume diaphragm) plus one
continuous quarter-annulus that grows outward with signal strength, drawn
over a full-size dimmed track so the whole 0-100% range stays visible.

No percentage is baked in -- wifi_signal.py buckets the live reading into
one of ten 10%-wide tiers, matching the same banding convention as
volume_color.py and backlight_level.py. A separate "off" state (dimmed
glyph + diagonal strike-through, same idea as bluetooth's off icon) covers
the wifi radio being disabled.

Output: waybar/icons/wifi/{tier1..10,off}.svg, plus
waybar/wifi-icons-generated.css, which style.css @imports, mapping
"tier1".."tier10"/"off" classes (set by wifi_signal.py) to the matching
background-image.

Run manually to regenerate: ./generate_wifi_icons.py
"""
import math
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ICONS_DIR = ROOT / "icons" / "wifi"
CSS_OUT = ROOT / "wifi-icons-generated.css"

WHITE = "#ffffff"
DIM_OPACITY = "0.3"

# Pivot at bottom-center; the whole glyph sweeps the 90 degrees centered on
# "straight up" (-135 to -45 in atan2-style degrees, 0 = right, y-down), so
# it fans symmetrically up-left/up-right instead of pointing off at a
# diagonal, in a 14x14 viewBox.
CX, CY = 7.0, 12.2
START_DEG, END_DEG = -135, -45  # up-left -> up-right
OUTER_RADIUS = 6.8

# A tight, symmetric box around the actual glyph (not the arbitrary 14x14
# space it was positioned in) -- CSS background-position: center centers
# *this* box, so if it were left as the full square, the glyph's own
# lopsided margins (tall gap above, thin sliver below the pivot) would make
# it look shifted down relative to the surrounding text.
_half_span = OUTER_RADIUS * math.cos(math.radians(45))
_PAD = 0.3
VIEW_X = CX - _half_span - _PAD
VIEW_Y = CY - OUTER_RADIUS - _PAD
VIEW_W = 2 * _half_span + 2 * _PAD
VIEW_H = OUTER_RADIUS + 2 * _PAD  # top = CY - OUTER_RADIUS, bottom = CY (the pivot tip)


def point(radius, deg):
    rad = math.radians(deg)
    return CX + radius * math.cos(rad), CY + radius * math.sin(rad)


def pie_slice(radius, opacity):
    x0, y0 = point(radius, START_DEG)
    x1, y1 = point(radius, END_DEG)
    return (
        f'<path d="M{CX:.2f} {CY:.2f} L{x0:.3f} {y0:.3f} A{radius} {radius} 0 0 1 {x1:.3f} {y1:.3f} Z" '
        f'fill="{WHITE}" fill-opacity="{opacity}"/>'
    )


def ring_segment(r_in, r_out, opacity):
    xi0, yi0 = point(r_in, START_DEG)
    xi1, yi1 = point(r_in, END_DEG)
    xo1, yo1 = point(r_out, END_DEG)
    xo0, yo0 = point(r_out, START_DEG)
    d = (
        f'M{xi0:.3f} {yi0:.3f} '
        f'A{r_in} {r_in} 0 0 1 {xi1:.3f} {yi1:.3f} '
        f'L{xo1:.3f} {yo1:.3f} '
        f'A{r_out} {r_out} 0 0 0 {xo0:.3f} {yo0:.3f} Z'
    )
    return f'<path d="{d}" fill="{WHITE}" fill-opacity="{opacity}"/>'


DOT_RADIUS = 1.7
RING_INNER = DOT_RADIUS - 0.15  # slight overlap, not just flush -- avoids an antialiasing seam at the join
N_TIERS = 10
RING_OUTER_BY_TIER = {
    tier: RING_INNER + tier * (OUTER_RADIUS - RING_INNER) / N_TIERS
    for tier in range(1, N_TIERS + 1)
}
GREY_TRACK = ring_segment(RING_INNER, OUTER_RADIUS, DIM_OPACITY)

# Off state: the whole glyph dimmed (no growth, just the full dot+track
# silhouette) plus a diagonal strike-through, same idea as bluetooth's off
# icon -- a slash across most of the glyph's bounding box.
OFF_SLASH = (
    f'<line x1="{VIEW_X + VIEW_W * 0.12:.3f}" y1="{VIEW_Y + VIEW_H * 0.1:.3f}" '
    f'x2="{VIEW_X + VIEW_W * 0.88:.3f}" y2="{VIEW_Y + VIEW_H * 0.95:.3f}" '
    f'stroke="{WHITE}" stroke-opacity="{DIM_OPACITY}" stroke-width="0.9" stroke-linecap="round"/>'
)
OFF_SHAPES = pie_slice(DOT_RADIUS, DIM_OPACITY) + GREY_TRACK + OFF_SLASH


def _svg(shapes):
    # Large intrinsic width/height (vs. the tight viewBox below) for the same
    # reason as generate_battery_icons.py: GTK's background-image loader
    # rasterizes once at the declared intrinsic size, then stretches that
    # bitmap to the CSS box, so a small intrinsic size makes for a blurry
    # upscale regardless of the eventual display size.
    intrinsic_h = 280
    intrinsic_w = round(intrinsic_h * VIEW_W / VIEW_H)
    view_box = f'{VIEW_X:.3f} {VIEW_Y:.3f} {VIEW_W:.3f} {VIEW_H:.3f}'
    return (
        f'<svg width="{intrinsic_w}" height="{intrinsic_h}" viewBox="{view_box}" '
        f'xmlns="http://www.w3.org/2000/svg">{shapes}</svg>'
    )


def wifi_svg(tier):
    return _svg(pie_slice(DOT_RADIUS, "1") + GREY_TRACK + ring_segment(RING_INNER, RING_OUTER_BY_TIER[tier], "1"))


def main():
    if ICONS_DIR.exists():
        shutil.rmtree(ICONS_DIR)
    ICONS_DIR.mkdir(parents=True)

    css_rules = ["/* GENERATED by generate_wifi_icons.py -- do not edit by hand */"]
    for tier in range(1, N_TIERS + 1):
        out_path = ICONS_DIR / f"tier{tier}.svg"
        out_path.write_text(wifi_svg(tier))
        css_rules.append(f'#custom-wifi.tier{tier} {{ background-image: url("file://{out_path}"); }}')

    off_path = ICONS_DIR / "off.svg"
    off_path.write_text(_svg(OFF_SHAPES))
    css_rules.append(f'#custom-wifi.off {{ background-image: url("file://{off_path}"); }}')

    CSS_OUT.write_text("\n".join(css_rules) + "\n")
    print(f"Wrote {len(list(ICONS_DIR.glob('*.svg')))} icons to {ICONS_DIR}")
    print(f"Wrote {CSS_OUT}")


if __name__ == "__main__":
    main()
