#!/usr/bin/env python3
"""Render the two states of the waybar custom/mode glyph: white on
transparent, same visual language as the other bar icons.

  wide-tile.svg: three rounded rectangles laid out like the actual
                 ultrawide-dwindle layout -- one full-height pane on the
                 right, two stacked panes on the left:
                     |   |   |
                     |---|   |
                     |   |   |
  float.svg:     three scattered rounded rectangles, like loose floating
                 windows at different sizes/positions rather than a tidy
                 grid -- no outer frame, just the three panes themselves.

Output: waybar/icons/mode/{wide-tile,float}.svg, plus
waybar/mode-icons-generated.css, which style.css @imports, mapping
"wide-tile"/"float" classes (set by hypr/mode_status.sh) to the matching
background-image.

Run manually to regenerate: ./generate_mode_icons.py
"""
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ICONS_DIR = ROOT / "icons" / "mode"
CSS_OUT = ROOT / "mode-icons-generated.css"

WHITE = "#ffffff"
RX = 1.5


def rect(x, y, w, h, opacity="1"):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{RX}" fill="{WHITE}" fill-opacity="{opacity}"/>'


# --- wide-tile: right pane full height, left column split top/bottom ---
MARGIN, GAP = 1.5, 1.5
COL_W = (20 - 2 * MARGIN - GAP) / 2
LEFT_H = (20 - 2 * MARGIN - GAP) / 2
RIGHT_X = MARGIN + COL_W + GAP

WIDE_TILE = (
    rect(MARGIN, MARGIN, COL_W, LEFT_H)
    + rect(MARGIN, MARGIN + LEFT_H + GAP, COL_W, LEFT_H)
    + rect(RIGHT_X, MARGIN, COL_W, 20 - 2 * MARGIN)
)

# --- float: three staggered panes. No two share an x-start, x-end,
# y-start, or y-end, so the combined silhouette is an irregular stepped
# polygon rather than everything's edges lining up into one big rectangle.
# Same opacity as all-white would just merge the overlaps into a blob, so
# each pane steps up in opacity so the one "in front" (drawn last) stays
# distinguishable from the ones it covers.
FLOAT = (
    rect(1, 2, 8, 7, opacity="0.55")
    + rect(8, 4, 8.5, 13, opacity="0.8")
    + rect(2.5, 8, 7.5, 7, opacity="1")
)

FILES = {"wide-tile": WIDE_TILE, "float": FLOAT}


def svg(shapes):
    # Large intrinsic width/height (vs. the 20x20 viewBox) for the same
    # reason as generate_battery_icons.py: GTK's background-image loader
    # rasterizes once at the declared intrinsic size, then stretches that
    # bitmap to the CSS box, so a small intrinsic size makes for a blurry
    # upscale regardless of the eventual display size.
    return f'<svg width="320" height="320" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">{shapes}</svg>'


def main():
    if ICONS_DIR.exists():
        shutil.rmtree(ICONS_DIR)
    ICONS_DIR.mkdir(parents=True)

    css_rules = ["/* GENERATED by generate_mode_icons.py -- do not edit by hand */"]
    for name, shapes in FILES.items():
        out_path = ICONS_DIR / f"{name}.svg"
        out_path.write_text(svg(shapes))
        css_rules.append(f'#custom-mode.{name} {{ background-image: url("file://{out_path}"); }}')

    CSS_OUT.write_text("\n".join(css_rules) + "\n")
    print(f"Wrote {len(list(ICONS_DIR.glob('*.svg')))} icons to {ICONS_DIR}")
    print(f"Wrote {CSS_OUT}")


if __name__ == "__main__":
    main()
