#!/bin/bash
# Toggle waybar between its neon palette (colors-neon.css, generated by
# generate_colors.py from palettes/*.toml) and a plain monochrome/white
# scheme (colors-mono.css), by flipping the colors.css symlink both
# style.css (@import) and the custom/battery + custom/volume scripts
# (hardcoded COLORS_CSS path) read through. That symlink target is the
# single variable that decides which scheme is active.
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LINK="$DIR/colors.css"
CURRENT="$(readlink "$LINK" 2>/dev/null)"

if [ "$CURRENT" = "colors-mono.css" ]; then
    ln -sf colors-neon.css "$LINK"
else
    ln -sf colors-mono.css "$LINK"
fi

pkill -SIGUSR2 waybar 2>/dev/null
exit 0
