wallpaper {
    monitor = 
    path = ~/dotfiles/wallpapers/black-use-my-time-smalltext-hires-cropped.png
    order = random
    timeout = 900
    path = ~/wallpapers
    fit_mode = cover
}

splash = false
