general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/zach/wallpapers/words-wallpapers/3-neistat-risk.png # blurs your current screen; or use a file path
    #blur_passes = 1
    #blur_size = 3
    brightness = 0.9
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(255, 255, 255)
    placeholder_text = <i>Password...</i>
    position = 0, -700
    #halign = center
    #valign = center
}

label {
    monitor =
    text = <span weight="bold">$TIME</span>
    text = $TIME
    color = rgba(255, 255, 255, 0.9)
    font_size = 150
    font_family = SF Pro
    position = 0, 300
    halign = center
    valign = center 
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    color = rgba(255, 255, 255, 0.8)
    font_size = 25
    font_family = SF Pro
    position = 0, 425
    halign = center
    valign = center
}

# label {
#     monitor =
#     text = cmd[update:15000] ~/.config/hypr/hyprlock_battery.sh
#     color = rgba(255, 255, 255, 0.7)
#     font_size = 18
#     font_family = sans
#     position = -40, 30
#     halign = right
#     valign = bottom
# }
