-- Generated by nwg-displays on 2026-07-15 at 19:56:53. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "879x1440",
    scale = 1.67
})
hl.monitor({
    output = "DP-1",
    mode = "3440x1440@59.97",
    position = "2604x1078",
    scale = 1.0
})
