-- Generated by nwg-displays on 2026-07-25 at 13:22:23. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "1626x2807",
    scale = 1.7000000000000006
})
hl.monitor({
    output = "DP-1",
    mode = "3440x1440@59.97",
    position = "3320x1596",
    scale = 1.0
})
