-- Generated by nwg-displays on 2026-08-07 at 17:10:32. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "3x362",
    scale = 1.67
})
hl.monitor({
    output = "DP-1",
    mode = "4096x2160@24.0",
    position = "1728x0",
    scale = 1.0
})
